name: CI Pipeline

on:
  push:
    branches:
      - main #this means CI Pipeline will trigger only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 #This action checks out the repository code
    - name: Set up Python
      uses: actions/setup-python@v4 #sets up a python enviroment
      with:
        python-version: "3.9" #version of python you want to use
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
    - name: Run tests
      run: pytest
      
